name: Lint CI
on:
  pull_request:
  push:
    branches:
      - '!master'
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js v18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm v8.x
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install deps
        run: pnpm un @tenx-ui/bff-client -s && pnpm install
        # run: pnpm install --only=dev --ignore-scripts && pnpm add react -D --only=dev --ignore-scripts

      - name: Lint
        run: npm run lint
